### GET /
GET http://localhost:5000


###
POST http://localhost:5003/auth/register
Content-Type: application/json

{
    "username": "Warlord@gmail.com",
    "password": "123232122"
}

### LOGIN a user POST /AUTH/LOGIN
POST http://localhost:5003/auth/login
Content-Type: application/json

{
    "username": "Warlord@gmail.com",
    "password": "123232122"
}


### Fetch all toods GET /TODOS (protected)
GET http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY4NDg5MjA0LCJleHAiOjE3Njg1NzU2MDR9.RjKPfyxfK1ItTAH1_Cvj54Tj31obuVGKWHlPvyVC8o4

### Creates a new todo POST /TODOS (protected)
POST http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY4NDg5MjA0LCJleHAiOjE3Njg1NzU2MDR9.RjKPfyxfK1ItTAH1_Cvj54Tj31obuVGKWHlPvyVC8o4
Content-Type: application/json

{
    "task": "Added tasks"
}

### Update a todo PUT /TODOS/:ID (protected)
PUT http://localhost:5003/todos/2?page=4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY4NDg5MjA0LCJleHAiOjE3Njg1NzU2MDR9.RjKPfyxfK1ItTAH1_Cvj54Tj31obuVGKWHlPvyVC8o4
Content-Type: application/json

{
    "completed": 1
}


### Delete a todo DELETE /TODOS/:ID (protected)
DELETE http://localhost:5003/todos/2`   
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY4NDg5MjA0LCJleHAiOjE3Njg1NzU2MDR9.RjKPfyxfK1ItTAH1_Cvj54Tj31obuVGKWHlPvyVC8o4
